### ISSUE TITLE
UI design issue

### ISSUE THREAD

**Issue by deep1296** [VaishnaviDhobale/Coach.com-clone#56]
- [x] Make the navbar items in proper alignment.

<img width="342" alt="image" src="https://github.com/VaishnaviDhobale/Coach.com-clone/assets/96063026/116ea5c5-1ef0-4b20-a291-bb6d0d2d0f7b">

**Comment by deep1296** [comment]
- [x] Footer content is getting aligned with the filter sidebar.

<img width="926" alt="image" src="https://github.com/VaishnaviDhobale/Coach.com-clone/assets/96063026/4a192b43-b117-4f85-a6b2-250c10b7b7c4">

**Comment by deep1296** [comment]
- [x] On the checkout divs are not in proper alignments.

<img width="925" alt="image" src="https://github.com/VaishnaviDhobale/Coach.com-clone/assets/96063026/d8f4fade-0b8f-4b2d-b22f-d627805f3ade">

**Comment by VaishnaviDhobale** [comment]
Reviewed and completed
