### ISSUE TITLE
Login route issue.

### ISSUE THREAD

**Issue by deep1296** [VaishnaviDhobale/Coach.com-clone#57]
- [x] While clicking on the login button nothing is there.

<img width="953" alt="image" src="https://github.com/VaishnaviDhobale/Coach.com-clone/assets/96063026/1bba6c9a-9817-495b-808c-9d486233c080">

<img width="938" alt="image" src="https://github.com/VaishnaviDhobale/Coach.com-clone/assets/96063026/0f12d7aa-aec9-48a7-b531-a7a6180da179">

**Comment by VaishnaviDhobale** [comment]
Reviewed and completed
